# Generated by Django 5.2.6 on 2025-09-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('brand', models.CharField(max_length=100, verbose_name='Hãng sản xuất')),
                ('model', models.CharField(max_length=100, verbose_name='Tên dòng máy')),
                ('cpu', models.CharField(blank=True, max_length=100, verbose_name='CPU')),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM (GB)')),
                ('storage', models.CharField(blank=True, max_length=100, verbose_name='Ổ cứng')),
                ('gpu', models.CharField(blank=True, max_length=100, verbose_name='GPU')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name='Hệ điều hành')),
                ('notes', models.TextField(blank=True, verbose_name='Ghi chú thêm')),
            ],
            options={
                'verbose_name': 'Dòng máy tính',
                'verbose_name_plural': 'Các dòng máy tính',
                'ordering': ['brand', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('asset_tag', models.CharField(max_length=50, unique=True, verbose_name='Mã tài sản')),
                ('serial', models.CharField(max_length=100, unique=True, verbose_name='Số serial')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Ngày mua')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Ngày hết hạn BH')),
                ('purchase_price', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Giá mua (VNĐ)')),
                ('status', models.CharField(choices=[('IN_STOCK', 'Trong kho'), ('ASSIGNED', 'Đã cấp phát'), ('RESERVED', 'Đã đặt trước'), ('REPAIR', 'Đang sửa chữa'), ('RETIRED', 'Đã bán/Cho đi'), ('DISPOSED', 'Đã thanh lý')], default='IN_STOCK', max_length=20, verbose_name='Trạng thái')),
                ('remark', models.TextField(blank=True, verbose_name='Ghi chú/Lý do')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='Phòng ban sử dụng')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee', verbose_name='Người sử dụng')),
            ],
            options={
                'verbose_name': 'Máy tính',
                'verbose_name_plural': 'Danh sách máy tính',
                'ordering': ['-purchase_date', 'asset_tag'],
            },
        ),
    ]
