# Generated by Django 5.2.6 on 2025-09-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='current_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='Vị trí hiện tại'),
        ),
        migrations.AlterUniqueTogether(
            name='computermodel',
            unique_together={('brand', 'model')},
        ),
        migrations.AddField(
            model_name='computer',
            name='computer_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.computermodel', verbose_name='Dòng máy'),
        ),
    ]
