# Generated by Django 5.2.6 on 2025-09-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='salvage_value',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Giá trị thanh lý ước tính (VNĐ)'),
        ),
        migrations.AddField(
            model_name='computer',
            name='useful_life',
            field=models.PositiveIntegerField(default=3, verbose_name='Vòng đời sử dụng (năm)'),
        ),
    ]
