# Generated by Django 5.2.6 on 2025-09-14 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã phòng ban')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phòng ban')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Phòng ban',
                'verbose_name_plural': 'Các phòng ban',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên chức vụ')),
                ('level', models.PositiveIntegerField(default=1, verbose_name='Cấp bậc')),
            ],
            options={
                'verbose_name': 'Chức vụ',
                'verbose_name_plural': 'Các chức vụ',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('emp_code', models.CharField(max_length=20, unique=True, verbose_name='Mã nhân viên')),
                ('full_name', models.CharField(max_length=100, verbose_name='Họ và tên')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.department', verbose_name='Phòng ban')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.position', verbose_name='Chức vụ')),
            ],
            options={
                'verbose_name': 'Nhân viên',
                'verbose_name_plural': 'Các nhân viên',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='accounts.employee', verbose_name='Trưởng phòng'),
        ),
    ]
