# Generated by Django 5.2.6 on 2025-09-14 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã vị trí')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vị trí')),
                ('type', models.CharField(choices=[('WAREHOUSE', 'Kho'), ('DEPARTMENT', 'Văn phòng/Phòng ban'), ('VENDOR_REPAIR', 'Nhà cung cấp (Sửa chữa)'), ('DISPOSAL', 'Nơi thanh lý')], max_length=20, verbose_name='Loại vị trí')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department', verbose_name='Phòng ban liên quan')),
            ],
            options={
                'verbose_name': 'Vị trí',
                'verbose_name_plural': 'Các vị trí',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('code', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Mã chứng từ')),
                ('type', models.CharField(choices=[('RECEIPT', 'Nhập kho'), ('ISSUE', 'Xuất cấp phát'), ('RETURN', 'Thu hồi/Trả về'), ('TRANSFER', 'Luân chuyển'), ('REPAIR_OUT', 'Gửi đi sửa'), ('REPAIR_IN', 'Nhận về từ sửa chữa'), ('WRITE_OFF', 'Báo hỏng/Mất'), ('DISPOSAL', 'Thanh lý')], max_length=20, verbose_name='Loại chứng từ')),
                ('status', models.CharField(choices=[('DRAFT', 'Nháp'), ('SUBMITTED', 'Đã gửi'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Từ chối'), ('POSTED', 'Đã ghi sổ')], default='DRAFT', max_length=20, verbose_name='Trạng thái CT')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_txns', to='accounts.employee', verbose_name='Người duyệt')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_txns', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.department', verbose_name='Phòng ban yêu cầu')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_txns', to='accounts.employee', verbose_name='Người xuất kho')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_txns', to='accounts.employee', verbose_name='Người nhận')),
                ('dest_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dest_txns', to='inventory.location', verbose_name='Nơi nhận')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_txns', to='inventory.location', verbose_name='Nơi xuất')),
            ],
            options={
                'verbose_name': 'Chứng từ kho',
                'verbose_name_plural': 'Các chứng từ kho',
            },
        ),
        migrations.CreateModel(
            name='InventoryTxnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('prev_status', models.CharField(blank=True, max_length=20, verbose_name='Trạng thái trước')),
                ('new_status', models.CharField(blank=True, max_length=20, verbose_name='Trạng thái mới')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú dòng')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.computer', verbose_name='Máy tính')),
                ('inventory_txn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorytxn', verbose_name='Chứng từ gốc')),
            ],
            options={
                'verbose_name': 'Dòng chứng từ',
                'verbose_name_plural': 'Các dòng chứng từ',
                'unique_together': {('inventory_txn', 'computer')},
            },
        ),
    ]
