# Generated by Django 5.2.6 on 2025-09-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytxn',
            name='posted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Ngày ghi sổ'),
        ),
    ]
