# Generated by Django 5.2.6 on 2025-09-18 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('inventory', '0002_inventorytxn_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytxnline',
            name='computer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history_lines', to='assets.computer', verbose_name='Máy tính'),
        ),
    ]
