# Generated by Django 5.2.6 on 2025-09-14 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('action', models.CharField(choices=[('CREATE', 'Tạo mới'), ('UPDATE', 'Cập nhật'), ('DELETE', 'Xóa'), ('STATUS_CHANGE', 'Thay đổi trạng thái')], max_length=20, verbose_name='Hành động')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID đối tượng')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu trước')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='Dữ liệu sau')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thay đổi')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Loại đối tượng')),
            ],
            options={
                'verbose_name': 'Nhật ký thay đổi',
                'verbose_name_plural': 'Nhật ký thay đổi',
            },
        ),
    ]
