# Generated by Django 5.2.6 on 2025-09-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='Số hóa đơn')),
                ('vendor', models.CharField(max_length=255, verbose_name='Nhà cung cấp')),
                ('date', models.DateField(verbose_name='Ngày hóa đơn')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng tiền (VNĐ)')),
            ],
            options={
                'verbose_name': 'Hóa đơn mua hàng',
                'verbose_name_plural': 'Hóa đơn mua hàng',
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Đơn giá (VNĐ)')),
                ('total_price', models.DecimalField(decimal_places=0, editable=False, max_digits=18, verbose_name='Thành tiền (VNĐ)')),
                ('computer_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.computermodel', verbose_name='Dòng máy')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseinvoice', verbose_name='Hóa đơn gốc')),
            ],
            options={
                'verbose_name': 'Dòng HĐ mua hàng',
                'verbose_name_plural': 'Dòng HĐ mua hàng',
            },
        ),
    ]
