# Generated by Django 5.2.6 on 2025-09-14 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('invoice_no', models.CharField(max_length=50, unique=True, verbose_name='Số hóa đơn')),
                ('customer', models.CharField(max_length=255, verbose_name='Khách hàng')),
                ('date', models.DateField(verbose_name='Ngày hóa đơn')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng doanh thu (VNĐ)')),
            ],
            options={
                'verbose_name': 'Hóa đơn bán hàng',
                'verbose_name_plural': 'Hóa đơn bán hàng',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Đơn giá bán (VNĐ)')),
                ('total_price', models.DecimalField(decimal_places=0, editable=False, max_digits=18, verbose_name='Thành tiền (VNĐ)')),
                ('cost_allocated', models.DecimalField(decimal_places=0, editable=False, max_digits=18, verbose_name='Giá vốn phân bổ (VNĐ)')),
                ('computer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.computer', verbose_name='Máy tính bán ra')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salesinvoice', verbose_name='Hóa đơn gốc')),
            ],
            options={
                'verbose_name': 'Dòng HĐ bán hàng',
                'verbose_name_plural': 'Dòng HĐ bán hàng',
            },
        ),
    ]
