# Generated by Django 5.2.6 on 2025-09-18 15:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('assets', '0002_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày đặt hàng')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Tổng tiền')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.employee', verbose_name='Nhân viên tạo đơn')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Số lượng')),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá tại thời điểm bán')),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.computer', verbose_name='Sản phẩm máy tính')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder', verbose_name='Đơn hàng')),
            ],
        ),
    ]
